sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest PHP_LINT=1
    - php: 7.0
      env: WP_VERSION=nightly WP_PHPCS=1
  fast_finish: true

before_script:
  - export WP_CORE_DIR=/tmp/wordpress/
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi
  - |
    if [[ "$WP_PHPCS" == "1" ]]; then
      composer install
      export PATH=$PATH:${PWD}/vendor/bin/
      # After CodeSniffer install you should refresh your path.
      phpenv rehash
    fi
  - export SP_DIR=${WP_CORE_DIR}wp-content/plugins/searchpress
  - git clone https://github.com/alleyinteractive/searchpress.git $SP_DIR


script:
  - if [[ "$PHP_LINT" == "1" ]]; then find . -type "f" -iname "*.php" | xargs -L "1" php -l; fi
  - if [[ "$WP_PHPCS" == "1" ]]; then phpcs -p -s -v -n --standard=./codesniffer.ruleset.xml --extensions=php .; fi
  - phpunit
  - phpunit -c multisite.xml
